export const PROFILE_TEXT = {
  EN: {
    title: 'Profile',
    loginTitle: 'Sign in to your account',
    loginDesc: 'Access your order history, saved preferences, and more.',
    loginButton: 'Sign in',
    guestTitle: 'Continue as guest',
    guestDesc: 'You can still place orders without signing in.',
    language: 'Language',
    support: 'Support',
    contactUs: 'Contact us',
    about: 'About',
    account: 'Account',
    orderHistory: 'Order history',
    signOut: 'Sign out',
    editProfile: 'Edit Profile',
    changePassword: 'Change password',
    emailNotVerified: 'Email not verified',
    verifyEmailDesc: 'Please verify your email to unlock all features.',
    verifyNow: 'Verify now',
    loadingProfile: 'Loading profile...',
    editProfileTitle: 'Edit profile',
    fullName: 'Full name',
    fullNamePlaceholder: 'Enter your full name',
    fullNameRequired: 'Full name is required',
    saveButton: 'Save changes',
    saving: 'Saving...',
    profileUpdated: 'Profile updated successfully!',
    updateFailed: 'Failed to update profile',
    errorOccurred: 'An error occurred',
    changePasswordTitle: 'Change password',
    currentPassword: 'Current password',
    newPassword: 'New password',
    confirmPassword: 'Confirm new password',
    currentPasswordPlaceholder: 'Enter current password',
    newPasswordPlaceholder: 'Enter new password',
    confirmPasswordPlaceholder: 'Confirm new password',
    currentPasswordRequired: 'Current password is required',
    newPasswordRequired: 'New password is required',
    passwordMinLength: 'Password must be at least 8 characters',
    confirmPasswordRequired: 'Please confirm your password',
    passwordsNoMatch: 'Passwords do not match',
    changePasswordButton: 'Change password',
    changingPassword: 'Changing...',
    passwordChanged: 'Password changed successfully!',
    changePasswordFailed: 'Failed to change password',
    passwordStrength: 'Password strength',
    weak: 'Weak',
    medium: 'Medium',
    strong: 'Strong',
    passwordRequirements: 'Password requirements',
    requirement8Chars: 'At least 8 characters',
    requirementUppercase: 'At least one uppercase letter',
    requirementLowercase: 'At least one lowercase letter',
    requirementNumber: 'At least one number',
    requirementSpecial: 'At least one special character',
  },
  VI: {
    title: 'Hồ sơ',
    loginTitle: 'Đăng nhập tài khoản',
    loginDesc: 'Truy cập lịch sử đơn hàng, tùy chọn đã lưu và nhiều hơn.',
    loginButton: 'Đăng nhập',
    guestTitle: 'Tiếp tục với tư cách khách',
    guestDesc: 'Bạn vẫn có thể đặt món mà không cần đăng nhập.',
    language: 'Ngôn ngữ',
    support: 'Hỗ trợ',
    contactUs: 'Liên hệ chúng tôi',
    about: 'Giới thiệu',
    account: 'Tài khoản',
    orderHistory: 'Lịch sử đơn hàng',
    signOut: 'Đăng xuất',
    editProfile: 'Chỉnh sửa hồ sơ',
    changePassword: 'Đổi mật khẩu',
    emailNotVerified: 'Email chưa xác thực',
    verifyEmailDesc: 'Vui lòng xác thực email để mở khóa tất cả tính năng.',
    verifyNow: 'Xác thực ngay',
    loadingProfile: 'Đang tải hồ sơ...',
    editProfileTitle: 'Chỉnh sửa hồ sơ',
    fullName: 'Họ và tên',
    fullNamePlaceholder: 'Nhập họ và tên',
    fullNameRequired: 'Họ và tên là bắt buộc',
    saveButton: 'Lưu thay đổi',
    saving: 'Đang lưu...',
    profileUpdated: 'Hồ sơ đã được cập nhật!',
    updateFailed: 'Cập nhật hồ sơ thất bại',
    errorOccurred: 'Đã xảy ra lỗi',
    changePasswordTitle: 'Đổi mật khẩu',
    currentPassword: 'Mật khẩu hiện tại',
    newPassword: 'Mật khẩu mới',
    confirmPassword: 'Xác nhận mật khẩu mới',
    currentPasswordPlaceholder: 'Nhập mật khẩu hiện tại',
    newPasswordPlaceholder: 'Nhập mật khẩu mới',
    confirmPasswordPlaceholder: 'Xác nhận mật khẩu mới',
    currentPasswordRequired: 'Mật khẩu hiện tại là bắt buộc',
    newPasswordRequired: 'Mật khẩu mới là bắt buộc',
    passwordMinLength: 'Mật khẩu phải có ít nhất 8 ký tự',
    confirmPasswordRequired: 'Vui lòng xác nhận mật khẩu',
    passwordsNoMatch: 'Mật khẩu không khớp',
    changePasswordButton: 'Đổi mật khẩu',
    changingPassword: 'Đang đổi...',
    passwordChanged: 'Mật khẩu đã được thay đổi!',
    changePasswordFailed: 'Đổi mật khẩu thất bại',
    passwordStrength: 'Độ mạnh mật khẩu',
    weak: 'Yếu',
    medium: 'Trung bình',
    strong: 'Mạnh',
    passwordRequirements: 'Yêu cầu mật khẩu',
    requirement8Chars: 'Ít nhất 8 ký tự',
    requirementUppercase: 'Ít nhất một chữ hoa',
    requirementLowercase: 'Ít nhất một chữ thường',
    requirementNumber: 'Ít nhất một số',
    requirementSpecial: 'Ít nhất một ký tự đặc biệt',
  },
}
