/**
 * Orders Feature - Constants (i18n text)
 */

export const ORDERS_TEXT = {
  EN: {
    title: 'Orders',
    currentSession: 'Current Session',
    noActiveOrder: 'No active order',
    noActiveOrderDesc: 'Place an order to see it here',
    paymentStatus: 'Payment',
    paid: 'Paid',
    unpaid: 'Unpaid',
    sessionNote: 'Payment received. Your session will close after all items are served.',
    sessionCompleted: 'Session completed',
    orderHistory: 'Order History',
    signInPrompt: 'Sign in to view your past orders',
    signInButton: 'Sign in',
    noPastOrders: 'No past orders yet',
    viewDetails: 'View details',
    items: 'items',
    viewTracking: 'View Tracking',
    payAmount: 'Pay',
    status: 'Status',
    orderDetails: 'Order Details',
    orderId: 'Order',
    date: 'Date',
    table: 'Table',
    completed: 'Completed',
    orderedItems: 'Ordered Items',
    quantity: 'Qty',
    size: 'Size',
    toppings: 'Add-ons',
    specialInstructions: 'Special Instructions',
    notes: 'Order Notes',
    noNotes: 'No notes',
    priceSummary: 'Price Summary',
    subtotal: 'Subtotal',
    tax: 'Tax',
    serviceCharge: 'Service charge',
    total: 'Total',
    paymentInfo: 'Payment Information',
    paymentMethod: 'Payment method',
    paidByCard: 'Paid by card',
    payAtCounter: 'Pay at counter',
    orderConfirmed: 'Order Confirmed',
    trackingOrder: 'Tracking Order',
  },
  VI: {
    title: 'Đơn hàng',
    currentSession: 'Phiên hiện tại',
    noActiveOrder: 'Không có đơn hàng',
    noActiveOrderDesc: 'Đặt món để xem tại đây',
    paymentStatus: 'Thanh toán',
    paid: 'Đã thanh toán',
    unpaid: 'Chưa thanh toán',
    sessionNote: 'Đã nhận thanh toán. Phiên của bạn sẽ đóng sau khi tất cả món được phục vụ.',
    sessionCompleted: 'Phiên đã hoàn thành',
    orderHistory: 'Lịch sử đơn hàng',
    signInPrompt: 'Đăng nhập để xem đơn hàng cũ',
    signInButton: 'Đăng nhập',
    noPastOrders: 'Chưa có đơn hàng cũ',
    viewDetails: 'Xem chi tiết',
    items: 'món',
    viewTracking: 'Xem theo dõi',
    payAmount: 'Thanh toán',
    status: 'Trạng thái',
    orderDetails: 'Chi tiết đơn hàng',
    orderId: 'Đơn hàng',
    date: 'Ngày',
    table: 'Bàn',
    completed: 'Đã hoàn thành',
    orderedItems: 'Món đã đặt',
    quantity: 'SL',
    size: 'Kích cỡ',
    toppings: 'Topping',
    specialInstructions: 'Yêu cầu đặc biệt',
    notes: 'Ghi chú đơn hàng',
    noNotes: 'Không có ghi chú',
    priceSummary: 'Tóm tắt giá',
    subtotal: 'Tạm tính',
    tax: 'Thuế',
    serviceCharge: 'Phí dịch vụ',
    total: 'Tổng cộng',
    paymentInfo: 'Thông tin thanh toán',
    paymentMethod: 'Phương thức',
    paidByCard: 'Đã thanh toán bằng thẻ',
    payAtCounter: 'Thanh toán tại quầy',
    orderConfirmed: 'Đơn hàng đã được xác nhận',
    trackingOrder: 'Theo dõi đơn hàng',
  },
}
