/**
 * Orders Feature - Constants & Mock Data
 */

import { Order } from './types';

export const TIMELINE_STEPS = ['placed', 'confirmed', 'preparing', 'ready', 'completed'] as const;

export const STEP_LABELS = {
  placed: 'Placed',
  confirmed: 'Confirmed',
  preparing: 'Preparing',
  ready: 'Ready',
  completed: 'Done',
} as const;

export const INITIAL_ORDERS: Order[] = [
  {
    id: '1',
    orderNumber: '#1247',
    table: 'Table 9',
    time: '1:45 PM',
    date: 'Dec 8, 2024',
    items: [
      { name: 'Chicken Wings', quantity: 1, price: 14.00, modifiers: ['Buffalo sauce', 'Extra crispy'] },
      { name: 'Onion Rings', quantity: 1, price: 7.00 },
      { name: 'Lemonade', quantity: 2, price: 4.00 },
    ],
    subtotal: 29.00,
    tax: 2.90,
    total: 31.90,
    paymentStatus: 'unpaid',
    orderStatus: 'placed',
    timeline: { placed: '1:45 PM' },
  },
  {
    id: '2',
    orderNumber: '#1246',
    table: 'Table 12',
    time: '1:30 PM',
    date: 'Dec 8, 2024',
    items: [
      { name: 'Sushi Platter', quantity: 1, price: 35.00, modifiers: ['No wasabi'] },
      { name: 'Miso Soup', quantity: 2, price: 4.50 },
      { name: 'Green Tea', quantity: 2, price: 3.00 },
    ],
    subtotal: 50.00,
    tax: 5.00,
    total: 55.00,
    paymentStatus: 'paid',
    orderStatus: 'confirmed',
    timeline: { placed: '1:30 PM', confirmed: '1:31 PM' },
  },
  {
    id: '3',
    orderNumber: '#1245',
    table: 'Table 5',
    time: '1:20 PM',
    date: 'Dec 8, 2024',
    items: [
      { name: 'Grilled Salmon', quantity: 1, price: 28.00 },
      { name: 'Steamed Vegetables', quantity: 1, price: 8.00 },
      { name: 'White Wine', quantity: 1, price: 12.00 },
    ],
    subtotal: 48.00,
    tax: 4.80,
    total: 52.80,
    paymentStatus: 'paid',
    orderStatus: 'ready',
    timeline: { placed: '1:20 PM', confirmed: '1:21 PM', preparing: '1:25 PM', ready: '1:45 PM' },
  },
  {
    id: '4',
    orderNumber: '#1244',
    table: 'Table 3',
    time: '12:45 PM',
    date: 'Dec 8, 2024',
    items: [
      { name: 'Margherita Pizza', quantity: 1, price: 16.00, modifiers: ['Extra cheese'] },
      { name: 'Caesar Salad', quantity: 1, price: 9.00 },
    ],
    subtotal: 25.00,
    tax: 2.50,
    total: 27.50,
    paymentStatus: 'paid',
    orderStatus: 'preparing',
    timeline: { placed: '12:45 PM', confirmed: '12:46 PM', preparing: '12:48 PM' },
  },
  {
    id: '5',
    orderNumber: '#1243',
    table: 'Table 8',
    time: '12:30 PM',
    date: 'Dec 8, 2024',
    items: [
      { name: 'Beef Burger', quantity: 2, price: 15.00, modifiers: ['No pickles'] },
      { name: 'French Fries', quantity: 2, price: 5.00 },
      { name: 'Milkshake', quantity: 1, price: 6.00 },
    ],
    subtotal: 46.00,
    tax: 4.60,
    total: 50.60,
    paymentStatus: 'paid',
    orderStatus: 'served',
    timeline: { placed: '12:30 PM', confirmed: '12:31 PM', preparing: '12:35 PM', ready: '12:48 PM', served: '1:00 PM' },
  },
  {
    id: '6',
    orderNumber: '#1242',
    table: 'Table 2',
    time: '12:05 PM',
    date: 'Dec 8, 2024',
    items: [
      { name: 'Pad Thai', quantity: 1, price: 18.00 },
      { name: 'Spring Rolls', quantity: 1, price: 8.00 },
      { name: 'Thai Iced Tea', quantity: 1, price: 4.00 },
    ],
    subtotal: 30.00,
    tax: 3.00,
    total: 33.00,
    paymentStatus: 'paid',
    orderStatus: 'completed',
    timeline: { placed: '12:05 PM', confirmed: '12:06 PM', preparing: '12:10 PM', ready: '12:25 PM', completed: '12:35 PM' },
  },
  {
    id: '7',
    orderNumber: '#1241',
    table: 'Table 7',
    time: '11:35 AM',
    date: 'Dec 8, 2024',
    items: [
      { name: 'Pasta Carbonara', quantity: 2, price: 18.50, modifiers: ['Extra bacon'] },
      { name: 'Garlic Bread', quantity: 1, price: 6.00 },
    ],
    subtotal: 43.00,
    tax: 4.30,
    total: 47.30,
    paymentStatus: 'paid',
    orderStatus: 'completed',
    timeline: { placed: '11:35 AM', confirmed: '11:36 AM', preparing: '11:38 AM', ready: '11:58 AM', completed: '12:02 PM' },
  },
  {
    id: '8',
    orderNumber: '#1240',
    table: 'Table 6',
    time: '11:15 AM',
    date: 'Dec 8, 2024',
    items: [
      { name: 'Chicken Salad', quantity: 1, price: 14.00 },
      { name: 'Sparkling Water', quantity: 1, price: 3.50 },
    ],
    subtotal: 17.50,
    tax: 1.75,
    total: 19.25,
    paymentStatus: 'refunded',
    orderStatus: 'cancelled',
    timeline: { placed: '11:15 AM', cancelled: '11:20 AM' },
  },
];
